/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_ValueExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_ValueExternal
#define _Included_ca_logaritm_dezel_view_display_external_ValueExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    getUnit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_getUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    getString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_getString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    getNumber
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_getNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    getBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_getBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueExternal
 * Method:    parse
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_ValueExternal_parse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
