/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_layout_LayoutNodeExternal */

#ifndef _Included_ca_logaritm_dezel_layout_LayoutNodeExternal
#define _Included_ca_logaritm_dezel_layout_LayoutNodeExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setId
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setLayout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setLayout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredBottom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredInnerWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredInnerWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredInnerHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredInnerHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredContentWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredContentWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredContentHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredContentHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredMarginTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredMarginTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredMarginLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredMarginLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredMarginRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredMarginRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredMarginBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredMarginBottom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredBorderTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredBorderTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredBorderLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredBorderLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredBorderRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredBorderRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredBorderBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredBorderBottom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredPaddingTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredPaddingTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredPaddingLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredPaddingLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredPaddingRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredPaddingRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getMeasuredPaddingBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getMeasuredPaddingBottom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getViewportWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getViewportWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    getViewportHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_getViewportHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    fillsParentWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_fillsParentWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    fillsParentHeight
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_fillsParentHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    wrapsContentWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_wrapsContentWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    wrapsContentHeight
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_wrapsContentHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    hasInvalidSize
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_hasInvalidSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    hasInvalidPosition
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_hasInvalidPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    hasInvalidLayout
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_hasInvalidLayout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setAnchorTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setAnchorTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setAnchorLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setAnchorLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setRight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setBottom
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setWidth
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setWidth
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setHeight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setHeight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinHeight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxHeight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentDirection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentDirection
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentLocation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentLocation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentAlignment
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentAlignment
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentWidth
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentWidth
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setContentHeight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setContentHeight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setBorderTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setBorderTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setBorderLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setBorderLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setBorderRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setBorderRight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setBorderBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setBorderBottom
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMarginTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMarginTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMarginLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMarginLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMarginRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMarginRight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMarginBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMarginBottom
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinMarginTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinMarginTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxMarginTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxMarginTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinMarginLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinMarginLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxMarginLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxMarginLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinMarginRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinMarginRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxMarginRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxMarginRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinMarginBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinMarginBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxMarginBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxMarginBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setPaddingTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setPaddingTop
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setPaddingLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setPaddingLeft
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setPaddingRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setPaddingRight
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setPaddingBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setPaddingBottom
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinPaddingTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinPaddingTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxPaddingTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxPaddingTop
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinPaddingLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinPaddingLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxPaddingLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxPaddingLeft
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinPaddingRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinPaddingRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxPaddingRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxPaddingRight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMinPaddingBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMinPaddingBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setMaxPaddingBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setMaxPaddingBottom
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setExpand
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setExpand
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setShrink
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setShrink
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_setVisible
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    invalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_invalidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    invalidateSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_invalidateSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    invalidatePosition
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_invalidatePosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    resolve
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_resolve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    measure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_measure
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    appendChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_appendChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    insertChild
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_insertChild
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutNodeExternal
 * Method:    removeChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutNodeExternal_removeChild
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
