/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_core_JavaScriptClassBuilderExternal */

#ifndef _Included_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
#define _Included_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createConstructor
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createConstructor
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createFunction
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createFunction
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createGetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createGetter
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createSetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createSetter
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createStaticFunction
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createStaticFunction
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createStaticGetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createStaticGetter
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptClassBuilderExternal
 * Method:    createStaticSetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptClassBuilderExternal_createStaticSetter
  (JNIEnv* , jclass, jlong, jlong, jstring, jstring, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
