/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_DisplayExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_DisplayExternal
#define _Included_ca_logaritm_dezel_view_display_external_DisplayExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    isInvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_isInvalid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    isResolving
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_isResolving
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    setWindow
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_setWindow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    setScale
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_setScale
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    setViewportWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_setViewportWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    setViewportHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_setViewportHeight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_external_DisplayExternal
 * Method:    setStylesheet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_DisplayExternal_setStylesheet
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
