/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_modules_i18n_TranslationManagerExternal */

#ifndef _Included_ca_logaritm_dezel_modules_i18n_TranslationManagerExternal
#define _Included_ca_logaritm_dezel_modules_i18n_TranslationManagerExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_modules_i18n_TranslationManagerExternal
 * Method:    load
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_modules_i18n_TranslationManagerExternal_load
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ca_logaritm_dezel_modules_i18n_TranslationManagerExternal
 * Method:    translate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_modules_i18n_TranslationManagerExternal_translate__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_logaritm_dezel_modules_i18n_TranslationManagerExternal
 * Method:    translate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_modules_i18n_TranslationManagerExternal_translate__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
