/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_style_StylerExternal */

#ifndef _Included_ca_logaritm_dezel_style_StylerExternal
#define _Included_ca_logaritm_dezel_style_StylerExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_style_StylerExternal
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_style_StylerExternal_create
  (JNIEnv *, jclass);

/*
 * Class:     ca_logaritm_dezel_style_StylerExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerExternal
 * Method:    setRoot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerExternal_setRoot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerExternal
 * Method:    load
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerExternal_load
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerExternal
 * Method:    setVariable
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerExternal_setVariable
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
