/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_layout_LayoutExternal */

#ifndef _Included_ca_logaritm_dezel_layout_LayoutExternal
#define _Included_ca_logaritm_dezel_layout_LayoutExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    create
 * Signature: (Lca/logaritm/dezel/layout/Layout;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    isInvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_isInvalid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    isResolving
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_isResolving
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    setRoot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_setRoot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    setViewportWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_setViewportWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    setViewportHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_setViewportHeight
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_layout_LayoutExternal
 * Method:    setScale
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_layout_LayoutExternal_setScale
  (JNIEnv *, jclass, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
