/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_StylesheetExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_StylesheetExternal
#define _Included_ca_logaritm_dezel_view_display_external_StylesheetExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_StylesheetExternal
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_StylesheetExternal_create
  (JNIEnv *, jclass);

/*
 * Class:     ca_logaritm_dezel_view_display_external_StylesheetExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_StylesheetExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_StylesheetExternal
 * Method:    setVariable
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_StylesheetExternal_setVariable
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     ca_logaritm_dezel_view_display_external_StylesheetExternal
 * Method:    evaluate
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_StylesheetExternal_evaluate
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
