/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_core_external_JavaScriptContextExternal */

#ifndef _Included_ca_logaritm_dezel_core_external_JavaScriptContextExternal
#define _Included_ca_logaritm_dezel_core_external_JavaScriptContextExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_create
  (JNIEnv* , jclass, jstring);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_delete
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    getGlobalObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_getGlobalObject
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    evaluate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_evaluate__JLjava_lang_String_2
  (JNIEnv* , jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    evaluate
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_evaluate__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv* , jclass, jlong, jstring, jstring);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    setAttribute
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_setAttribute
  (JNIEnv* , jclass, jlong, jint, jobject);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    getAttribute
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_getAttribute
  (JNIEnv* , jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    delAttribute
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_delAttribute
  (JNIEnv* , jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    setExceptionCallback
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_setExceptionCallback
  (JNIEnv* , jclass, jlong, jobject, jobject);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    throwError
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_throwError
  (JNIEnv* , jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_core_external_JavaScriptContextExternal
 * Method:    garbageCollect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_external_JavaScriptContextExternal_garbageCollect
  (JNIEnv* , jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
