/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_DisplayNodeExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_DisplayNodeExternal
#define _Included_ca_logaritm_dezel_view_display_DisplayNodeExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_create
  (JNIEnv* , jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_delete
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setDisplay
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setDisplay
  (JNIEnv* , jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setId
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setId
  (JNIEnv* , jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredTop
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredLeft
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredRight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredBottom
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredWidth
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredHeight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredInnerWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredInnerWidth
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredInnerHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredInnerHeight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredContentWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredContentWidth
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredContentHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredContentHeight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredMarginTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredMarginTop
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredMarginLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredMarginLeft
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredMarginRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredMarginRight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredMarginBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredMarginBottom
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredBorderTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredBorderTop
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredBorderLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredBorderLeft
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredBorderRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredBorderRight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredBorderBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredBorderBottom
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredPaddingTop
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredPaddingTop
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredPaddingLeft
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredPaddingLeft
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredPaddingRight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredPaddingRight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    getMeasuredPaddingBottom
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_getMeasuredPaddingBottom
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setAnchorTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setAnchorTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setAnchorLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setAnchorLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setRight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setBottom
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setWidth
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setWidth
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinWidth
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxWidth
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setHeight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setHeight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinHeight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxHeight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentDirection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentDirection
  (JNIEnv* , jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentLocation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentLocation
  (JNIEnv* , jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentAlignment
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentAlignment
  (JNIEnv* , jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentWidth
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentWidth
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setContentHeight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setContentHeight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setBorderTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setBorderTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setBorderLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setBorderLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setBorderRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setBorderRight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setBorderBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setBorderBottom
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMarginTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMarginTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMarginLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMarginLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMarginRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMarginRight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMarginBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMarginBottom
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinMarginTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinMarginTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxMarginTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxMarginTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinMarginLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinMarginLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxMarginLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxMarginLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinMarginRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinMarginRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxMarginRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxMarginRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinMarginBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinMarginBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxMarginBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxMarginBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setPaddingTop
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setPaddingTop
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setPaddingLeft
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setPaddingLeft
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setPaddingRight
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setPaddingRight
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setPaddingBottom
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setPaddingBottom
  (JNIEnv* , jclass, jlong, jint, jint, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinPaddingTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinPaddingTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxPaddingTop
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxPaddingTop
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinPaddingLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinPaddingLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxPaddingLeft
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxPaddingLeft
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinPaddingRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinPaddingRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxPaddingRight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxPaddingRight
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMinPaddingBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMinPaddingBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setMaxPaddingBottom
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setMaxPaddingBottom
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setExpandFactor
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setExpandFactor
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setShrinkFactor
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setShrinkFactor
  (JNIEnv* , jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_setVisible
  (JNIEnv* , jclass, jlong, jboolean);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    resolve
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_resolve
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    measure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_measure
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    appendChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_appendChild
  (JNIEnv* , jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    insertChild
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_insertChild
  (JNIEnv* , jclass, jlong, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    removeChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_removeChild
  (JNIEnv* , jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    isFillingParentWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_isFillingParentWidth
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    isFillingParentHeight
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_isFillingParentHeight
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    isWrappingContentWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_isWrappingContentWidth
  (JNIEnv* , jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_DisplayNodeExternal
 * Method:    isWrappingContentHeight
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_view_display_DisplayNodeExternal_isWrappingContentHeight
  (JNIEnv* , jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
