/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal */

#ifndef _Included_ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal
#define _Included_ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal
 * Method:    createFunction
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal_createFunction
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal
 * Method:    createGetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal_createGetter
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal
 * Method:    createSetter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_core_JavaScriptObjectBuilderExternal_createSetter
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
