/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_PropertyExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_PropertyExternal
#define _Included_ca_logaritm_dezel_view_display_external_PropertyExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_PropertyExternal
 * Method:    getValues
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_PropertyExternal_getValues
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
