/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_ValueListExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_ValueListExternal
#define _Included_ca_logaritm_dezel_view_display_external_ValueListExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueListExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_view_display_external_ValueListExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueListExternal
 * Method:    getCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_view_display_external_ValueListExternal_getCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_ValueListExternal
 * Method:    getValue
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_ValueListExternal_getValue
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
