/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_view_display_external_FunctionValueExternal */

#ifndef _Included_ca_logaritm_dezel_view_display_external_FunctionValueExternal
#define _Included_ca_logaritm_dezel_view_display_external_FunctionValueExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_view_display_external_FunctionValueExternal
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_view_display_external_FunctionValueExternal_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_FunctionValueExternal
 * Method:    getArguments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_view_display_external_FunctionValueExternal_getArguments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_view_display_external_FunctionValueExternal
 * Method:    getArgument
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_view_display_external_FunctionValueExternal_getArgument
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
