/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_logaritm_dezel_style_StylerNodeExternal */

#ifndef _Included_ca_logaritm_dezel_style_StylerNodeExternal
#define _Included_ca_logaritm_dezel_style_StylerNodeExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setId
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setStyler
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setStyler
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setType
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setType
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setVisible
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    appendChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_appendChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    insertChild
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_insertChild
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    removeChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_removeChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    appendShadowedNode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_appendShadowedNode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    removeShadowedNode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_removeShadowedNode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    appendStyle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_appendStyle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    removeStyle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_removeStyle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    appendState
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_appendState
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    removeState
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_removeState
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    resolve
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_resolve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getData
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemProperty
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemProperty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemValueType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemValueType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemValueType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemValueType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemValueUnit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemValueUnit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemValueUnit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemValueUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemValueWithString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemValueWithString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemValueAsString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemValueAsString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemValueWithNumber
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemValueWithNumber
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemValueAsNumber
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemValueAsNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemValueWithBoolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemValueWithBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemValueAsBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemValueAsBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    setItemData
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_setItemData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ca_logaritm_dezel_style_StylerNodeExternal
 * Method:    getItemData
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ca_logaritm_dezel_style_StylerNodeExternal_getItemData
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
